version: '3.7'
services:
  server:
    container_name: bot-server
    image: node:14.1.0-buster
    build: .
    command: yarn dev
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
    depends_on:
      - db
      - redis
  db:
    image: mongo:latest
    container_name: bot-db
    env_file:
      - .env
    volumes:
      - ./local-data/db:/data/db
    ports:
      - 27017:27017
