version: "3.7"
services:
  bot:
    container_name: bot
    image: node:14.1.0-buster
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
